---

# Extras

- name: Installing command-line applications
  homebrew: name={{item}} state=present
  with_items:
    - mpv
    - imagemagick



- name: Configuring Ubersicht
  git: repo=https://github.com/herrbischoff/nerdbar.widget dest="/Users/{{username}}/Library/Application Support/Übersicht/widgets/nerdbar.widget"
  