---

# Extras

- name: Installing command-line applications
  homebrew: name={{item}} state=present
  with_items:
    - mpv
    - imagemagick

- name: Installing GUI applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - firefox
    - google-chrome
    - ubersicht
    - alfred
    - flux
    - transmission
    - gimp
    - keepassx
    - libreoffice
    - amethyst
    - dropbox

- name: Configuring Ubersicht
  git: repo=https://github.com/herrbischoff/nerdbar.widget dest="/Users/{{username}}/Library/Application Support/Übersicht/widgets/nerdbar.widget"
