---

# Javascript

- name: Installing Node Version Manager
  homebrew: name=nvm state=present

- name: Configuring NVM folder
  file: state=directory name=/Users/{{username}}/.nvm

- name: Installing latest NodeJS
  shell: export NVM_DIR=~/.nvm && . $(brew --prefix nvm)/nvm.sh && nvm install {{node_version}}

- name: Default latest NodeJS Version
  shell: export NVM_DIR=~/.nvm && . $(brew --prefix nvm)/nvm.sh && nvm alias default {{node_version}}

- name: Installing Frontend tools
  shell: export NVM_DIR=~/.nvm && . $(brew --prefix nvm)/nvm.sh && npm install -g npm bower gulp webpack nodemon phantomjs-prebuilt
