---

# Python

- name: Installing system python
  homebrew: name={{item}} state=present
  with_items:
    - python
    - python3

- name: Checking Pythonz installation
  register: pythonz
  stat: path=/usr/local/pythonz

- name: Downloading Pythonz installer
  when: pythonz.stat.exists == False
  get_url:
    url: https://raw.github.com/saghul/pythonz/master/pythonz-install
    dest: /tmp/pythonz-install.sh
    mode: 0444

- name: Installing Pythonz
  when: pythonz.stat.exists == False
  become_user: "{{username}}"
  command: /bin/bash /tmp/pythonz-install.sh

- name: Checking Python virtualenv installation
  register: virtualenvwrapper
  stat: path=/usr/bin/virtualenvwrapper.sh

- name: Installing Python virtualenv
  when: virtualenvwrapper.stat.exists == False
  shell: pip install virtualenvwrapper
