---

# Code editors

- name: Installing VIM bundle (spf13-vim)
  sudo_user: "{{username}}"
  shell: curl http://j.mp/spf13-vim3 -L -o - | sh

- name: Updating bundles and VIM configurations
  copy: src={{item}} dest="/home/{{username}}/" owner={{username}} group={{username}}
  with_items:
    - .vimrc.before.local
    - .vimrc.local

- name: Updating VIM Vundle plugins
  sudo_user: "{{username}}"
  shell: vim +BundleInstall +qall && vim +BundleClean +qall

- name: Compiling ycm_support_libs (YouCompleteMe)
  sudo_user: "{{username}}"
  shell: ./install.sh --clang-completer chdir="/home/{{username}}/.vim/bundle/YouCompleteMe/"

