---

# Code editors

- name: Installing NeoVim requirements (according to this configuration)
  pacman: name=the_silver_searcher state=present

- name: Installing NeoBundle
  become_user: "{{username}}"
  git: repo=https://github.com/Shougo/neobundle.vim dest="/home/{{username}}/.nvim/bundle/neobundle.vim"

- name: Adding neovim dependency from pip system libraries
  pip: name=neovim

- name: Creating fonts folders
  file: path={{item}} state=directory owner="{{username}}" group="{{username}}"
  with_items:
    - "/home/{{username}}/.fonts/"
    - "/home/{{username}}/.config/fontconfig/conf.d/"

- name: Downloading fonts
  become_user: "{{username}}"
  get_url: url={{item.url}} dest={{item.dest}}
  with_items:
      - { url: "https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf", dest: "/home/{{username}}/.fonts/" }
      - { url: "https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf", dest: "/home/{{username}}/.config/fontconfig/conf.d/" }

- name: Updating font cache
  become_user: "{{username}}"
  shell: fc-cache -vf "/home/{{username}}/.fonts/"
