---

# Contains common plays that must be run as first task

- name: Installing system packages
  homebrew: name={{item}} state=present
  with_items:
    - fzf
    - tree
    - zsh
    - wget
    - ag
    - mono
    - htop

- name: Installing support tools [1/2]
  homebrew_cask: name=osxfuse state=present
    
- name: Installing support tools [2/2]
  homebrew: name={{item}} state=present
  with_items:
    - homebrew/fuse/encfs
    - p7zip
    - unrar
    - archey

- name: Creating 'programs' folder
  file: path="/Users/{{username}}/programs" owner={{username}} group=staff state=directory

- name: Creating 'workspaces' folder
  file: path="/Users/{{username}}/workspaces" owner={{username}} group=staff state=directory
