---
- hosts: dev-machine
  user: root
  sudo: yes

  vars:
  - ansible_python_interpreter: /usr/bin/python2

  tasks:
  - include: common/tasks/system.yml tags=system
  - include: common/tasks/virtualization.yml tags=virtualization
  - include: common/tasks/browser.yml tags=browser
  - include: common/tasks/development.yml tags=development
  - include: common/tasks/ide.yml tags=ide
  - include: common/tasks/postgresql.yml tags=postgresql