---

# Overview: configuring a developer machine in just minutes

- hosts: all
  remote_user: root

  tasks:
    - name: Checking required variables
      fail: msg="Variable '{{item}}' is not defined."
      when: "{{item}} is not defined"
      with_items:
        - fullname
        - email
        - username

- hosts: all
  remote_user: root
  sudo: yes

  roles:
    - system
    - shell
    - provisioning
    - postgresql
    - redis
    - development
    - extras
    - editors
    - awesome
    - { role: dotfiles, tags: ['dotfiles'] }
