---

# Overview: configuring a developer machine in just minutes

- hosts: default
  tasks:
    - name: Checking required variables
      fail: msg="Variable '{{item}}' is not defined."
      when: "{{item}} is not defined"
      with_items:
        - fullname
        - email
        - username

- hosts: default
  become: yes
  vars_files:
    - variables/versions.yml
  roles:
    - system
    - shell
    - vm
    - provisioning
    - cluster
    - postgresql
    - redis
    - development
    - extras
    - editors
    - bspwm
    - fonts
    - { role: dotfiles, tags: ['dotfiles'] }
