---

# Dotfiles

- name: Cloning all dotfiles to the HOME directory
  become_user: "{{username}}"
  git: repo=https://github.com/palazzem/dotfiles.git dest="/home/{{username}}/.dotfiles" accept_hostkey=yes

- name: Removing old files (if any)
  file: state=absent name={{item}}
  with_items:
    - "/home/{{username}}/.xinitrc"
    - "/home/{{username}}/.zshrc"
    - "/home/{{username}}/.config/nvim/init.vim"
    - "/home/{{username}}/.config/bspwm/bspwmrc"

- name: Creating required directories
  file: state=directory name={{item}}
  with_items:
    - "/home/{{username}}/.config/nvim/"
    - "/home/{{username}}/.config/bspwm/"

- name: Creating symbolic links
  file: state=link src={{item.src}} dest={{item.dest}} owner={{username}} group={{username}}
  with_items:
      - { src: "/home/{{username}}/.dotfiles/xinitrc", dest: "/home/{{username}}/.xinitrc" }
      - { src: "/home/{{username}}/.dotfiles/zshrc", dest: "/home/{{username}}/.zshrc" }
      - { src: "/home/{{username}}/.dotfiles/config/nvim/nvimrc", dest: "/home/{{username}}/.config/nvim/init.vim" }
      - { src: "/home/{{username}}/.dotfiles/config/bspwm/bspwmrc", dest: "/home/{{username}}/.config/bspwm/bspwmrc" }
