---
# Development configuration

- name: Installing Version Control Systems
  pacman: name=git,mercurial,gitg,meld state=installed

- name: Installing Heroku toolbelt
  register: heroku
  shell: wget -qO- https://toolbelt.heroku.com/install.sh | sh

- name: Installing Pythonz
  register: pythonz
  shell: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  sudo_user: $username

- name: Installing PIP
  pacman: name=python2-pip state=installed

- name: Installing Python virtualenv
  register: virtualenvwrapper
  shell: pip2 install virtualenvwrapper

- name: Installing system Ruby
  pacman: name=ruby state=installed

- name: Installing Ruby RVM
  register: rvm
  shell: \curl -L https://get.rvm.io | bash -s
  sudo_user: $username

- name: Installing Java Development Kit
  command: yaourt -S jdk

- name: Installing Jython
  pacman: name=jython state=installed

- name: Installing Maven
  pacman: name=maven state=installed

- name: Installing Ant
  pacman: name=apache-ant state=installed

- name: Installing Node Version Manager (NVM)
  register: nvm
  shell: curl https://raw.github.com/creationix/nvm/master/install.sh | sh
  sudo_user: $username

- name: Installing latest NodeJS 0.8.x
  sudo_user: $username
  shell: nvm install 0.8

- name: Default latest NodeJS Version
  sudo_user: $username
  shell: nvm alias default 0.8

- name: Installing Bower
  sudo_user: $username
  shell: npm install bower -g

- name: Installing Yeoman (Yo)
  sudo_user: $username
  shell: npm install -g yo grunt-cli

- name: Downloading Seam Framework
  sudo_user: $username
  get_url: url=$seam dest=/tmp/seam.tar.gz

- name: Installing Seam Framework
  sudo_user: $username
  command: tar -xzf /tmp/seam.tar.gz -C /home/${username}/extra/