---
# Development configuration

- name: Installing Version Control Systems
  pacman: name=git,mercurial,gitg,meld state=installed

- name: Configuring GIT defaults
  template: src=common/templates/.gitconfig.j2 dest=/home/${username}/.gitconfig owner=$username group=$username mode=0644 backup=yes

- name: Checking Heroku toolbelt installation
  register: inst_heroku
  file: path=/usr/local/heroku state=directory

- name: Installing Heroku toolbelt
  shell: wget -qO- https://toolbelt.heroku.com/install.sh | sh
  when_changed: $inst_heroku

- name: Checking Pythonz installation
  register: inst_pythonz
  file: path=/home/${username}/.pythonz state=directory

- name: Installing Pythonz
  shell: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  sudo_user: palazzem
  when_changed: $inst_pythonz

- name: Installing PIP
  pacman: name=python2-pip state=installed

- name: Checking Python virtualenv installation
  register: inst_virtualenvwrapper
  file: path=/usr/bin/virtualenvwrapper.sh

- name: Installing Python virtualenv
  shell: pip2 install virtualenvwrapper
  when_changed: $inst_virtualenvwrapper

- name: Installing system Ruby
  pacman: name=ruby state=installed

- name: Checking Ruby RVM installation
  register: inst_rvm
  file: path=/home/${username}/.rvm state=directory

- name: Installing Ruby RVM
  shell: \curl -L https://get.rvm.io | bash -s stable
  sudo_user: palazzem
  when_changed: $inst_rvm

- name: Checking Java Development Kit installation
  register: inst_java
  file: path=/opt/java state=directory

- name: Installing Java Development Kit
  command: yaourt -S jdk creates=/opt/java
  when_changed: $inst_java

- name: Installing Maven
  pacman: name=maven state=installed

- name: Installing Ant
  pacman: name=apache-ant state=installed

- name: Installing Node Version Manager (NVM)
  register: inst_nvm
  git: repo=git://github.com/creationix/nvm.git dest=/home/${username}/.nvm
  sudo_user: palazzem

- name: Checking Seam Framework installation
  register: inst_seam
  file: path=/home/${username}/extra/jboss-seam-2.3.0.Final state=directory

- name: Downloading Seam Framework
  sudo_user: palazzem
  get_url: url=$seam dest=/var/tmp/seam.tar.gz
  when_changed: $inst_seam

- name: Installing Seam Framework
  sudo_user: palazzem
  command: tar -xzf /var/tmp/seam.tar.gz -C /home/${username}/extra/
  when_changed: $inst_seam

- name: Configuring .bashrc
  sudo_user: palazzem
  template: src=common/templates/.bashrc.j2 dest=/home/${username}/.bashrc owner=$username group=$username mode=0644 backup=yes