---
# Some useful programs / tools

- name: Installing GIMP
  pacman: name=gimp state=installed

- name: Installing Keepassx
  pacman: name=keepassx state=installed

- name: Installing VLC
  pacman: name=vlc state=installed

- name: Installing xChat
  pacman: name=xchat state=installed