---
# Some useful programs / tools

- name: Installing GIMP
  sudo: yes
  apt: pkg=gimp state=latest

- name: Installing Keepassx
  sudo: yes
  apt: pkg=keepassx state=latest

- name: Installing VLC
  sudo: yes
  apt: pkg=vlc state=latest

- name: Installing xChat
  sudo: yes
  apt: pkg=xchat state=latest