---
# Configuration of postgresql server

- name: Installing PostgreSQL server
  sudo: yes
  apt: pkg=postgresql,python-psycopg2,pgadmin3 state=installed

- name: Configuring postgres user
  sudo: yes
  ignore_errors: yes
  postgresql_user: user=postgres password=$psqlpassword state=present
  sudo_user: postgres

- name: Copying default configuration files
  sudo: yes
  copy: src=common/files/pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf owner=postgres group=postgres mode=0600 backup=yes