---
# Arch Linux basic configuration

- name: Installing basic system packages
  pacman: name=sudo,alsa-utils,xf86-video-intel,xf86-input-synaptics,openssh,vim,yaourt,tar,zip,unzip,p7zip,wget,curl state=installed, update_cache=yes

- name: Installing Xorg and LXDE Desktop Environment
  pacman: name=xorg-server,xorg-server-utils,mesa,lxde,lxdm state=installed

- name: Enabling LXDM display manager
  service: name=lxdm enabled=yes

- name: Creating user group
  group: name=$username state=present

- name: Creating user
  user: name=$username group=$username password=$userpass generate_ssh_key=true ssh_key_bits=4096 state=present