---
# Ubuntu basic configuration

- name: Updating all packages
  sudo: yes
  apt: upgrade=yes update_cache=yes state=latest

- name: Installing basic system packages
  sudo: yes
  apt: pkg=vim,p7zip,curl state=latest update_cache=yes

- name: Creating program folder inside user home for IDEs and frameworks
  file: path=/home/${username}/program owner=$username group=$username state=directory