---
# Configuring Virtualization tools

- name: Installing KVM
  apt: name=qemu-kvm,libvirt-bin,ubuntu-vm-builder,bridge-utils,virt-manager state=latest

- name: Put user in libvirtd group
  user: name=$username groups=libvirtd