---

# Contains common plays that must be run as first task

- name: Adding Yaourt (AUR) repository
  lineinfile: dest=/etc/pacman.conf state=present line={{item.line}}
  with_items:
    - { line: '"[archlinuxfr]"' }
    - { line: '" SigLevel = Never"' }
    - { line: '" Server = http://repo.archlinux.fr/$arch"' }

- name: Installing system packages
  pacman: name={{item}} state=present update_cache=yes
  with_items:
    - base-devel
    - sudo
    - alsa-utils
    - openssh
    - yaourt
    - wicd

- name: Installing support tools
  pacman: name={{item}} state=present
  with_items:
    - p7zip
    - curl
    - vim
    - tar
    - zip
    - unzip
    - wget
    - mlocate

- name: Installing video drivers
  pacman: name={{item}} state=present
  with_items:
    - xf86-video-intel
    - xf86-video-fbdev
    - xf86-video-vesa
    - xf86-input-synaptics

- name: Installing X
  pacman: name={{item}} state=present
  with_items:
    - xorg-server
    - xorg-server-utils
    - mesa

- name: Installing desktop environment or a window manager
  pacman: name={{desktop}} state=present

- name: Adding default user
  user: name={{username}} shell=/bin/bash groups=wheel append=yes

- name: Creating a default SSH key
  user: name={{username}} generate_ssh_key=yes ssh_key_bits=4096 ssh_key_file=.ssh/id_rsa

- name: Creating 'program' folder
  file: path="/home/{{username}}/program" owner={{username}} group={{username}} state=directory

- name: Adding 'wheel' group to sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) ALL'"

