---

# Contains common plays that must be run as first task

- name: Installing system packages
  pacman: name={{item}} state=present update_cache=yes
  with_items:
    - base-devel
    - sudo
    - alsa-utils
    - xf86-video-intel
    - xf86-input-synaptics
    - openssh

- name: Installing support tools
  pacman: name={{item}} state=present
  with_items:
    - p7zip
    - curl
    - vim
    - tar
    - zip
    - unzip
    - wget
    - mlocate

- name: Installing window manager (Awesome!)
  pacman: name={{item}} state=present
  with_items:
    - xorg-server
    - xorg-server-utils
    - mesa
    - awesome

- name: Adding default user
  user: name=palazzem shell=/bin/bash groups=wheel append=yes

- name: Creating a default SSH key
  user: name=palazzem generate_ssh_key=yes ssh_key_bits=4096 ssh_key_file=.ssh/id_rsa

- name: Creating 'program' folder
  file: path=/home/palazzem/program owner=palazzem group=palazzem state=directory

