---

# Contains common plays that must be run as first task

- name: Installing dependencies and support tools
  pacman: name={{item}} state=present update_cache=yes
  with_items:
    - vim
    - p7zip
    - curl

- name: Install development tools
  pacman: name={{item}} state=present
  with_items:
    - base-devel

- name: Add default user
  user: name=palazzem shell=/bin/bash groups=wheel append=yes

- name: Create a default SSH key
  user: name=palazzem generate_ssh_key=yes ssh_key_bits=4096 ssh_key_file=.ssh/id_rsa

- name: Create 'program' folder
  file: path=/home/palazzem/program owner=palazzem group=palazzem state=directory

