---

# Docker

- name: Installing Docker Engine
  homebrew_cask: name=docker state=present

- name: Installing Docker tools
  homebrew: name={{item}} state=present
  with_items:
    - docker-compose
    - docker-machine
