---

# Heroku Toolbelt

- name: Checking Heroku toolbelt installation
  register: heroku
  stat: path=/usr/local/heroku

- name: Downloading Heroku Toolbelt
  get_url:
    url: https://toolbelt.heroku.com/install.sh
    dest: /tmp/heroku-install.sh
    mode: 0440
  when: heroku.stat.exists == False

- name: Installing Heroku toolbelt
  command: /bin/bash /tmp/heroku-install.sh
  when: heroku.stat.exists == False
