---

# Javascript

- name: Checking previous NVM installation
  register: nvm
  stat: path=/home/palazzem/.nvm

- name: Installing Node Version Manager (NVM)
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash
  sudo_user: palazzem
  when: nvm.stat.exists == False

- name: Installing latest NodeJS 0.12.x
  sudo_user: palazzem
  shell: source ~/.nvm/nvm.sh && nvm install 0.12

- name: Default latest NodeJS Version
  sudo_user: palazzem
  shell: source ~/.nvm/nvm.sh && nvm alias default 0.12

- name: Installing Frontend toolchain
  sudo_user: palazzem
  shell: source ~/.nvm/nvm.sh && npm install -g bower yo grunt-cli gulp karma-cli coffee-script phantomjs protractor chdir=/home/palazzem/

- name: Updating webdriver
  sudo_user: palazzem
  shell: source ~/.nvm/nvm.sh && webdriver-manager update

