---

# Javascript

- name: Checking previous NVM installation
  register: nvm
  stat: "path=/home/{{username}}/.nvm"

- name: Downloading Node Version Manager (NVM)
  when: nvm.stat.exists == False
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh
    dest: /tmp/nvm-install.sh
    mode: 0444

- name: Installing Node Version Manager (NVM)
  when: nvm.stat.exists == False
  become_user: "{{username}}"
  command: /bin/bash /tmp/nvm-install.sh

- name: Installing latest NodeJS v5.6.0
  become_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && nvm install v5.6.0

- name: Default latest NodeJS Version
  become_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && nvm alias default v5.6.0

# Ignoring errors because 'sometimes' NPM stops working
- name: Installing Frontend toolchain
  become_user: "{{username}}"
  ignore_errors: yes
  shell: source ~/.nvm/nvm.sh && npm install -g npm bower gulp webpack phantomjs-prebuilt
