---

# Javascript

- name: Checking previous NVM installation
  register: nvm
  stat: "path=/home/{{username}}/.nvm"

- name: Downloading Node Version Manager (NVM)
  when: nvm.stat.exists == False
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh
    dest: /tmp/nvm-install.sh
    mode: 0444

- name: Installing Node Version Manager (NVM)
  when: nvm.stat.exists == False
  become_user: "{{username}}"
  command: /bin/bash /tmp/nvm-install.sh

- name: Installing latest NodeJS 0.12.x
  become_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && nvm install 0.12

- name: Default latest NodeJS Version
  become_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && nvm alias default 0.12

- name: Installing Frontend toolchain
  become_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && npm install -g bower yo grunt-cli gulp karma-cli ember-cli coffee-script phantomjs protractor ionic cordova chdir="/home/{{username}}/"

- name: Updating webdriver
  become_user: "{{username}}"
  shell: source ~/.nvm/nvm.sh && webdriver-manager update

