---

# Python

- name: Checking Pythonz installation
  register: pythonz
  stat: path=/usr/local/pythonz

- name: Installing Pythonz
  sudo_user: palazzem
  when: pythonz.stat.exists == False
  shell:
    executable=/bin/bash
    curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash


- name: Installing PIP
  pacman: name={{item}} state=present
  with_items:
    - python-pip
    - python2-pip

- name: Checking Python virtualenv installation
  register: virtualenvwrapper
  stat: path=/usr/bin/virtualenvwrapper.sh

- name: Installing Python virtualenv
  shell: pip install virtualenvwrapper
  when: virtualenvwrapper.stat.exists == False

