---

# bspwm window manager

- name: Installing bspwm window manager with support tools
  pacman: name={{item}} state=present
  with_items:
    - bspwm
    - sxhkd
    - stalonetray
    - feh
    - ranger
    - w3m
    - rofi
    - gvfs
    - gvfs-afc
    - gvfs-smb
    - gvfs-mtp
    - pcmanfm
    - xarchiver
    - xlockmore

- name: Be aware of the .local/bin folder
  file: path="/home/{{username}}/.local/bin" state=directory owner={{username}} group={{username}}
