---

# Virtualbox

- name: Installing Virtualbox
  pacman: name=virtualbox state=present

- name: Adding Virtualbox modules
  lineinfile: dest=/etc/modules-load.d/virtualbox.conf state=present line={{item}}
  with_items:
    - "vboxdrv"
    - "vboxnetadp"
    - "vboxnetflt"
    - "vboxpci"

- name: Adding user to vboxusers group
  user: name={{username}} shell=/bin/bash groups=vboxusers append=yes
