---

# Google Cloud SDK

- name: Google Cloud SDK - creating required directories
  file: state=directory name={{item}} owner={{username}} group={{username}}
  with_items:
    - "/home/{{username}}/programs/google-cloud-sdk/"

- name: Google Cloud SDK - installing
  unarchive: src=https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-107.0.0-linux-x86_64.tar.gz dest=/home/{{username}}/programs/google-cloud-sdk copy=no owner={{username}} group={{username}}
