---

# Awesome window manager

- name: Installing Awesome window manager
  pacman: name={{item}} state=present
  with_items:
    - awesome
    - gvfs
    - gvfs-afc
    - gvfs-smb
    - gvfs-mtp
    - gnome-terminal
    - pcmanfm
    - xarchiver
    - xscreensaver
    - archlinux-xdg-menu
    - lua-filesystem

- name: Adding auxiliar scripts
  copy: src={{item}} dest=/usr/bin/ owner=root group=root mode=0755
  with_items:
    - battery
    - awesome-menu-update
    - lock-suspend

- name: Creating Awesome config directory
  file: state=directory dest="/home/{{username}}/.config/awesome/" owner={{username}} group={{username}}

- name: Adding generic configurations
  copy: src={{item}} dest="/home/{{username}}/.config/awesome/{{item}}" owner={{username}} group={{username}}
  with_items:
    - variables.lua

- name: Adding .xinitrc
  copy: src=.xinitrc dest="/home/{{username}}/" owner={{username}} group={{username}} backup=yes

- name: Generating Awesome menu
  sudo_user: "{{username}}"
  command: xdg_menu --format awesome --root-menu /etc/xdg/menus/arch-applications.menu > /home/{{username}}/.config/awesome/archmenu.lua

